spring:
  application:
    name: mailNotifierService
  profiles:
    active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mailnotifierdb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true


brevo:
  api-url: ${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}
  api-key: ${BREVO_API_KEY}
  sender-email: ${BREVO_SENDER_EMAIL}
  sender-name: ${BREVO_SENDER_NAME}
